/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.pipelines.errors.formatting

import org.apache.spark.sql.AnalysisException
import org.apache.spark.sql.pipelines.graph.QueryOrigin


object AnalysisExceptionFormatter {

  /**
   * Returns a context string that shows the user-defined query, and points to the location that is
   * relevant to this origin.
   *
   * The output of this looks like -
   *
   * {{{
   * == SQL of Table tableName (line 1, position 1) ==
   * SELECT * FROM tableName
   * --------------^^^
   * }}}
   */
  def buildContextString(origin: QueryOrigin): Option[String] = {
    origin.sqlText match {
      case Some(query) =>
        (origin.line, origin.startPosition) match {
          case (Some(line), Some(startPosition)) =>
            val lines = query.split("\n")
            if ((line < 1 || line > lines.size) ||
              (startPosition < 0 || startPosition > lines(line - 1).length)) {
              // Don't return anything if the line or position is out of bounds.
              None
            } else {
              // Split into two sets based on the line number.
              // We add the "----^^^" part as a new line between these two sets.
              val (above, below) = lines.splitAt(line)
              val builder = new StringBuilder()

              // Build the header which looks like either -
              // If object type and object name are available -
              // == SQL of <objectType> <objectName> (line <line>, position <startPosition>) ==
              //
              // Otherwise
              // == SQL ==
              builder ++= "\n== SQL"
              if (origin.objectType.isDefined && origin.objectName.isDefined) {
                builder ++= s" of ${origin.objectType.get} ${origin.objectName.get} " +
                  s"(line $line, position $startPosition)"
              }
              builder ++= " ==\n"

              // Start building the SQL text part of the message
              // First add the lines before the position pointer
              above.foreach(builder ++= _ += '\n')
              // Then add the position pointers
              builder ++= (0 until startPosition)
                .map(_ => "-")
                .mkString("") ++= "^^^\n"
              // Finally add the lines after the position pointer
              below.foreach(builder ++= _ += '\n')
              Option(builder.toString())
            }
          case _ => None
        }
      case _ => None
    }
  }

  /**
   * Formats an [[AnalysisException]].
   *
   * AnalysisException structure -
   * - AnalysisExceptions have a `line` and `startPosition` field. These values are set in the
   *   context of the SQL text that actually generated this exception when it was parsed / analyzed.
   * - AnalysisExceptions have a base message in the `message` field. The message shown to the user
   *   is a modified string generated by the `getMessage` function, which is what we override in
   *   [[FormattedAnalysisException]].
   *
   * Formatting logic -
   * - We need to go on a case by case basis in updating `getMessage`
   *   since different subclasses of AnalysisException might have overridden `getMessage` in a
   *   different way. We risk adding too much information or losing information by blinding
   *   modifying `getMessage`. For instance, `ParseException` already returns SQL text pointing to
   *   user code in its `getMessage` implementation.
   * - Currently, we only re-format error messages that are specifically instances of
   *   `AnalysisException` or `ExtendedAnalysisException`. We propagate the SQL text that generated
   *   the exception in the `origin` field. We combine this with the original error message and the
   *   lineNumber and startPosition fields in AnalysisException to generate an error message that
   *   includes both the SQL text and pointers to the problematic line.
   * - We don't re-format error messages for other types of AnalysisException. Nevertheless, we do
   *   update the error class and set it to `fallbackErrorClass` if it isn't already set.
   */
  private[errors] def format(
      ex: AnalysisException,
      origin: QueryOrigin,
      fallbackErrorClass: String): FormattedAnalysisException = {
    val errorClass = ex.errorClass.getOrElse(fallbackErrorClass)
//    val cause = ErrorFormatter.format(ex.getCause, fallbackErrorClass, origin)
    val newOrigin = origin.merge(QueryOrigin(line = ex.line, startPosition = ex.startPosition))
    val newMessage: String = ex match {
      case _
          if ex.getClass.getName == "org.apache.spark.sql.AnalysisException" ||
          ex.getClass.getName == "org.apache.spark.sql.catalyst.ExtendedAnalysisException" =>
        (
          Seq(ex.message) ++
          buildContextString(newOrigin).toSeq
        ).mkString("\n")
      case _ => ex.getMessage()
    }
    new FormattedAnalysisException(
      originalEx = ex,
      origin = newOrigin,
      errorClass = errorClass,
      message = newMessage,
      ex.getCause
//      cause = cause
    )
  }
}
