#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _FlowType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FlowTypeEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FlowType.ValueType], builtins.type
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    APPEND: _FlowType.ValueType  # 5
    """Flow writes to its destination in append (streaming) mode."""
    MATERIALIZED_VIEW: _FlowType.ValueType  # 7
    """Flow writes to a materialized view."""
    VIEW: _FlowType.ValueType  # 8
    """Flow outputs to a view."""
    UNKNOWN: _FlowType.ValueType  # 9
    """Unknown flow type. Used, for example, when we can't determine the
    output mode of a streaming flow.
    """

class FlowType(_FlowType, metaclass=_FlowTypeEnumTypeWrapper):
    """The type of a flow. Due to some weirdness with proto code generation,
    enums have to be unique within a package, not just a message.
    Some types conflict with `DatasetType`.

    Next ID = 10;
    """

APPEND: FlowType.ValueType  # 5
"""Flow writes to its destination in append (streaming) mode."""
MATERIALIZED_VIEW: FlowType.ValueType  # 7
"""Flow writes to a materialized view."""
VIEW: FlowType.ValueType  # 8
"""Flow outputs to a view."""
UNKNOWN: FlowType.ValueType  # 9
"""Unknown flow type. Used, for example, when we can't determine the
output mode of a streaming flow.
"""
global___FlowType = FlowType
